<?php

namespace Drupal\no_access_reference_label\Plugin\Field\FieldFormatter;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\EntityReferenceFieldItemListInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Field\Plugin\Field\FieldFormatter\EntityReferenceLabelFormatter;
use Drupal\Core\Entity\Exception\UndefinedLinkTemplateException;
use Drupal\Core\TypedData\TranslatableInterface;


/**
 * Plugin implementation of the 'entity reference label' formatter.
 *
 * @FieldFormatter(
   *   id = "no_access_entity_reference_label",
 *   label = @Translation("No Access Label"),
 *   description = @Translation("Display the label of the referenced entities."),
 *   field_types = {
 *     "entity_reference"
 *   }
 * )
 */
class NoAccessEntityReferenceLabelFormatter extends EntityReferenceLabelFormatter {
  /**
   * {@inheritdoc}
   */
  protected function checkAccess(EntityInterface $entity) {
    return parent::checkAccess($entity); // TODO: Change the autogenerated stub
  }


  public function viewElements(FieldItemListInterface $items, $langcode) {
    $elements = array();
    $link_setting = $this->getSetting('link');

    foreach ($this->getEntitiesToView($items, $langcode) as $delta => $entity) {
      if ($this->isUnpublishedEntity($entity)) {
        continue;
      }
      $label = $entity->label();
      // If the link is to be displayed and the entity has a uri, display a
      // link.
      $output_as_link = $link_setting && $entity->access('view', NULL, FALSE);
      if ($output_as_link && !$entity->isNew()) {
        try {
          $uri = $entity->urlInfo();
        }
        catch (UndefinedLinkTemplateException $e) {
          // This exception is thrown by \Drupal\Core\Entity\Entity::urlInfo()
          // and it means that the entity type doesn't have a link template nor
          // a valid "uri_callback", so don't bother trying to output a link for
          // the rest of the referenced entities.
          $output_as_link = FALSE;
        }
      }

      if ($output_as_link && isset($uri) && !$entity->isNew()) {
        $elements[$delta] = [
          '#type' => 'link',
          '#title' => $label,
          '#url' => $uri,
          '#options' => $uri->getOptions(),
        ];

        if (!empty($items[$delta]->_attributes)) {
          $elements[$delta]['#options'] += array('attributes' => array());
          $elements[$delta]['#options']['attributes'] += $items[$delta]->_attributes;
          // Unset field item attributes since they have been included in the
          // formatter output and shouldn't be rendered in the field template.
          unset($items[$delta]->_attributes);
        }
      }
      else {
        $elements[$delta] = array('#plain_text' => $label);
      }
      $elements[$delta]['#cache']['tags'] = $entity->getCacheTags();
    }

    return $elements;
  }

  /**
   * Checks if a entity is unpublished.
   *
   * @param \Drupal\Core\Entity\EntityInterface $entity
   */
  protected function isUnpublishedEntity(EntityInterface $entity) {
    // @todo Actually check ;) .
    return FALSE;
  }

  protected function getEntitiesToView(EntityReferenceFieldItemListInterface $items, $langcode) {
    $entities = array();

    foreach ($items as $delta => $item) {
      // Ignore items where no entity could be loaded in prepareView().
      if (!empty($item->_loaded)) {
        $entity = $item->entity;

        // Set the entity in the correct language for display.
        if ($entity instanceof TranslatableInterface) {
          $entity = \Drupal::entityManager()->getTranslationFromContext($entity, $langcode);
        }

        // Add the referring item, in case the formatter needs it.
        $entity->_referringItem = $items[$delta];
        $entities[$delta] = $entity;
      }
    }

    return $entities;
  }


}
